experiment:
  seeds: [1]
  n: 10
  random_labels: false
  betas: [100, 500, 1000, .inf]
  epochs: 4000000
  eta: 1.0e-5
  m: 10000
  L: 3
  activation: tanh
  dataset: digits
  init_type: standard
  use_linearized: true
  same_noise: true
  track_jacobian: true
  tracked_metrics:
    - train_loss
    - feat_gram_lambda
    - lin_train_loss
    - lin_param_dist
    - nn_lin_param_dist
    - jacobian_dist
  jac_probe_size: 10
  device: cuda
  gpu_indices: [1]
  track_every: 50000
  print_every: 1000000
  checkpoint_state: sharded_state #  metrics_only

run:
  ckpt_dir: "~/cld_optimization_experiments/cld_checkpoints"
  save_ckpt: true
