experiment:
    seeds: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
    n: 10
    random_labels: false
    betas: [100, 500, 1000, .inf]
    epochs: 2000000
    eta: 1.0e-5
    m: 159056
    dataset: digits
    init_type: standard
    same_noise: true
    use_linearized: true
    track_jacobian: false
    device: cuda
    track_every: 10000
    print_every: 100000
  
run:
    ckpt_dir: "~/cld_checkpoints/expr1"
    save_ckpt: true
    load_ckpt: false
    load_ckpt_name: ".pt"
    resume_from_ckpt: false
    new_total_epochs: 0